#!/bin/bash

umount "${systemrescue_data_dir}/sysrescue/build_into_srm/var/backups/systemrescue-backup/backupdb" &>/dev/null
umount "${systemrescue_data_dir}/sysrescue/build_into_srm/etc/resticprofile" &>/dev/null

if [[ -d "${systemrescue_data_dir}/sysrescue/build_into_srm" ]]; then
    rm -rf "${systemrescue_data_dir}/sysrescue/build_into_srm" || exit 1
fi

if [[ -d "${systemrescue_temp_dir}/customize" ]]; then
    rm -rf "${systemrescue_temp_dir}/customize" || exit_fail 100 "Failed to clean up directory: ${systemrescue_temp_dir}/customize"
fi
