#!/bin/bash 

echoreg "Using SystemRescueCD Version: $systemrescue_cd_version"
echoreg "Using Restic Version: $restic_version"
echoreg "Using ResticProfile Version: $resticprofile_version"

# Create iniital required staging directories
mkdir -p "${systemrescue_cache_dir}" || exit_fail 100 "FATAL: Could not create systemrescue_cache_dir"
mkdir -p "${systemrescue_data_dir}/sysrescue/build_into_srm/usr/local/bin" || exit_fail 100 "FATAL: Could not create directory: ${systemrescue_data_dir}/sysrescue/build_into_srm/usr/local/bin"
mkdir -p "${systemrescue_temp_dir}/restic-install" || exit_fail 100 "FATAL: Could not create directory: ${systemrescue_temp_dir}/restic-install"

# Download, Extract, and Install if it's not cached already: restic
if [[ ! -f "${systemrescue_cache_dir}/restic_${restic_version}_linux_amd64.bz2" ]]; then
    curl -C - -Lso \
        "${systemrescue_cache_dir}/restic_${restic_version}_linux_amd64.bz2" \
        "$restic_url"
fi
bunzip2 -kf "${systemrescue_cache_dir}/restic_${restic_version}_linux_amd64.bz2" || exit_fail 101 "FATAL: Failed to extract restic binary"
chmod 755 "${systemrescue_cache_dir}/restic_${restic_version}_linux_amd64"
chown root:root "${systemrescue_cache_dir}/restic_${restic_version}_linux_amd64"
mv "${systemrescue_cache_dir}/restic_${restic_version}_linux_amd64" "${systemrescue_data_dir}/sysrescue/build_into_srm/usr/local/bin/restic" || exit_fail 102 "FATAL: Failed to move restic binary to sysrescue build directory"

# Download, Extract, and Install if it's not cached already: resticprofile
if [[ ! -f "${systemrescue_cache_dir}/resticprofile_${resticprofile_version}_linux_amd64.tar.gz" ]]; then
    curl -C - -Lso \
        "${systemrescue_cache_dir}/resticprofile_${resticprofile_version}_linux_amd64.tar.gz" \
        "$resticprofile_url"
        #"https://github.com/creativeprojects/resticprofile/releases/download/v${resticprofile_version}/resticprofile_${resticprofile_version}_linux_amd64.tar.gz" || return 1
fi
tar -xzf "${systemrescue_cache_dir}/resticprofile_${resticprofile_version}_linux_amd64.tar.gz" -C "${systemrescue_temp_dir}/restic-install" || exit_fail 101 "FATAL: Failed to extract resticprofile archive"
chmod 755 "${systemrescue_temp_dir}/restic-install/resticprofile"
chown root:root "${systemrescue_temp_dir}/restic-install/resticprofile"
mv "${systemrescue_temp_dir}/restic-install/resticprofile" "${systemrescue_data_dir}/sysrescue/build_into_srm/usr/local/bin/resticprofile" || exit_fail 102 "FATAL: Failed to move resticprofile binary to sysrescue build directory"
rm -rf "${systemrescue_temp_dir}/restic-install" || exit_fail 100 "FATAL: Failed to remove temporary restic-install directory"

# Copy resticprofile configuration to Disc staging directory
mkdir -p "${systemrescue_data_dir}/sysrescue/build_into_srm/etc/resticprofile"
if ! cp -a "${resticprofile_config_dir}/." "${systemrescue_data_dir}/sysrescue/build_into_srm/etc/resticprofile/"; then
    exit_fail 205 "FATAL: Failed to copy resticprofile config files over to recovery image build"
fi

add_to_squashfs "/usr/local/bin/restic m 755 root root"
add_to_squashfs "/usr/local/bin/resticprofile m 755 root root"
add_path_to_squashfs "${systemrescue_data_dir}/sysrescue/build_into_srm/etc/resticprofile" 700 600

# if $debug; then
#     echo "==========================================================================="
#     echo "Cache Dir: $systemrescue_cache_dir"
#     ls -lR "$systemrescue_cache_dir"
#     echo "====="
#     echo

#     echo "Data Dir: $systemrescue_data_dir"
#     ls -lR "$systemrescue_data_dir"
#     echo "====="
#     echo

#     echo "Temp Dir: $systemrescue_temp_dir"
#     ls -lR "$systemrescue_temp_dir"
#     echo "==========================================================================="

#     echo "SquashFS Definitions:"
#     echo 
#     cat "${systemrescue_data_dir}/sysrescue/build_into_srm/.squashfs-pseudo"
#     echo "==========================================================================="
# fi
