#!/bin/bash

restoreDir="$HOME/.borgmatic/restore"

hook_before() {
    mkdir -p "$restoreDir" || exit 1
    pushd "$restoreDir" || exit 2
    brew bundle dump || exit 3

    cat > restore.sh <<EOF
#!/bin/bash

if which brew; then
    echo "Installing Homebrew Bundle"
    brew bundle
else
    echo "Install Homebrew first using the following:"
    echo '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'
    echo "Re-run restore.sh after installing Homebrew to install Homebrew Bundle"
fi
EOF

    popd || exit 2
}

hook_after() {
    :
}

hook_fail() {
    :
}

hook_final() {
    :
}

case "$1" in
    before)     hook_before     || exit $?;;
    after)      hook_after      || exit $?;;
    fail)       hook_fail       || exit $?;;
    finally)    hook_final      || exit $?;;
esac
